name: python3-env
channels:
  - conda-forge
dependencies:
  - caproto
  - cothread
  - dateparser
  - dm-tree
  - epics-base
  - epicscorelibs
  - greenlet
  - h5py
  - hdf5
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab=3.4.3
  - matplotlib
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mpi
  - mpi4py
  - notebook
  - numexpr
  - numpy=1.23.5
  - openmpi
  - pandas
  - p4p=3.5.5
  - pip
  - pydm
  - pyepics
  - pyqt
  - pyqtgraph
  - pytest
  - python=3.8
  - pytz
  - pyzmq
  - qtpy
  - requests
  - scipy
  - seaborn
  - six
  - sqlite
  - sqlalchemy
  - xopt
  - pip:
    - git+https://github.com/slaclab/edmbutton
    - git+https://github.com/slaclab/edlgenerator
    - git+https://github.com/slaclab/slacepics
    - git+https://github.com/slaclab/subprocessca
    - git+https://github.com/slaclab/meme
    - git+https://github.com/slaclab/pyca
    - git+https://github.com/slaclab/lcls-live
    - git+https://github.com/slaclab/lcls-tools
